In [24]:
import requests
import pandas as pd


from Bio.PDB import PDBParser
from Bio.PDB.DSSP import DSSP
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import itertools
import matplotlib.patches as patches

import glob

# 1. Using AlphaFold API to download structures

In [ ]:
# AlphaFold Downloader for UniProt ID


def download_alphafold_pdb(uniprot_id, output_path=None):
    """
    Download the AlphaFold PDB structure for a given UniProt ID.
    
    Parameters:
    - uniprot_id (str): The UniProt ID (e.g., 'P69905')
    - output_path (str): Optional. Path to save the PDB file.
    
    Returns:
    - str: File path of the downloaded PDB file, or None if failed.
    """
    base_url = "https://alphafold.ebi.ac.uk/files"
    pdb_url = f"{base_url}/AF-{uniprot_id}-F1-model_v4.pdb"
    
    if output_path is None:
        output_path = f"{uniprot_id}.pdb"
    
    try:
        print(f"Fetching AlphaFold structure for UniProt ID: {uniprot_id}")
        response = requests.get(pdb_url)
        response.raise_for_status()
        
        with open(output_path, 'w') as file:
            file.write(response.text)
        
        print(f"✅ Download complete: {output_path}")
        return output_path
    
    except requests.HTTPError as http_err:
        print(f"❌ HTTP error occurred: {http_err}")
    except Exception as err:
        print(f"❌ Other error occurred: {err}")
    
    return None

# Example: Downloading Hemoglobin subunit alpha (UniProt ID: P69905)
download_alphafold_pdb("P11308")

Fetching AlphaFold structure for UniProt ID: P11308
✅ Download complete: P11308.pdb

'P11308.pdb'

In [9]:
lambert_TFs = pd.read_csv("../output/lambert_TFs_10-21-24_with_DBD_coords.csv")
lambert_TFs["uniprotID"] = lambert_TFs["id"].str.split("|").str[1]
lambert_TFs

,Unnamed: 0,id,ProteinSeq,DBD_coords_merged,uniprotID
0,0,sp|A0A087WUV0|ZN892_HUMAN Zinc finger protein ...,MEPEGRGSLFEDSDLLHAGNPKENDVTAVLLTPGSQELMIRDMAEA...,"[[221, 243], [249, 271], [277, 299], [305, 327...",A0A087WUV0
1,1,sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8...,MENEKENLFCEPHKRGLMKTPLKESTTANIVLAEIQPDFGPLTTPT...,"[[114, 182], [262, 347]]",A0AVK6
2,2,sp|A0PJY2|FEZF1_HUMAN Fez family zinc finger p...,MDSSCHNATTKMLATAPARGNMMSTSKPLAFSIERIMARTPEPKAL...,"[[260, 282], [288, 310], [316, 338], [344, 366...",A0PJY2
3,3,sp|A1A519|F170A_HUMAN Protein FAM170A OS=Homo ...,MKRRQKRKHLENEESQETAEKGGGMSKSQEDALQPGSTRVAKGWSQ...,"[[1, 330]]",A1A519
4,4,sp|A1YPR0|ZBT7C_HUMAN Zinc finger and BTB doma...,MANDIDELIGIPFPNHSSEVLCSLNEQRHDGLLCDVLLVVQEQEYR...,"[[364, 386], [392, 414], [420, 442], [448, 469]]",A1YPR0
...,...,...,...,...,...
1608,1608,sp|Q9Y6Q9|NCOA3_HUMAN Nuclear receptor coactiv...,MSGLGENLDPLASDSRKRKLPCDTPGQGLTCSGEKRRREQESKYIE...,"[[31, 83]]",Q9Y6Q9
1609,1609,sp|Q9Y6R6|Z780B_HUMAN Zinc finger protein 780B...,MVHGSVTFRDVAIDFSQEEWECLQPDQRTLYRDVMLENYSHLISLG...,"[[165, 187], [193, 215], [221, 243], [249, 271...",Q9Y6R6
1610,1610,sp|Q9Y6X0|SETBP_HUMAN SET-binding protein OS=H...,MESRETLSSSRQRGGESDFLPVSSAKPPAAPGCAGEPLLSTPGPGK...,"[[583, 596], [1015, 1027], [1450, 1462]]",Q9Y6X0
1611,1611,sp|Q9Y6X8|ZHX2_HUMAN Zinc fingers and homeobox...,MASKRKSTTPCMVRTSQVVEQDVPEEVDRAKEKGIGTPQPDVAKDS...,"[[78, 101], [110, 133], [271, 317], [442, 496]...",Q9Y6X8
1612,1612,sp|Q9Y6Y1|CMTA1_HUMAN Calmodulin-binding trans...,MWRAEGKWLPKTSRKSVSQSVFCGTSTYCVLNTVPPIEDDHGNSNS...,"[[69, 182]]",Q9Y6Y1

In [10]:
activator_TFs = pd.read_csv("../soto_analysis/outputs/all_TFs_table_proteins_activators.txt", sep = "\t")
activator_TFs

,Unnamed: 0,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length
0,0,NaN,NaN,A6NJG6,NaN,ENST00000334384,79-135,142-315,152-315,NaN,1
1,1,NaN,NaN,A8MTJ6,NaN,ENST00000428390,145-234,369-420,NaN,NaN,1
2,2,NaN,NaN,A8MYZ6,NaN,ENST00000641094,89-178,382-491,NaN,NaN,1
3,3,NaN,NaN,A8MZ59,NaN,ENST00000640845,31-65,92-181,22-101,NaN,1
4,4,NaN,NaN,O00321,NaN,ENST00000403402,242-321,1-162,22-121,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
441,441,NaN,NaN,Q9Y5R6,NaN,ENST00000382276,72-118,172-251,182-261,NaN,1
442,442,NaN,NaN,Q9Y5W3,NaN,ENST00000248071,"272-296,302-326,332-354",1-89,62-268,NaN,1
443,443,NaN,NaN,Q9Y692,NaN,ENST00000294409,89-165,422-573,"52-141,202-291",NaN,1
444,444,NaN,NaN,Q9Y6Q9,NaN,ENST00000371998,31-83,621-1424,"12-181,292-371,652-861",NaN,1
445,445,NaN,NaN,Q9Y6Y1,NaN,ENST00000303635,69-182,"702-841,422-501","282-361,472-721,822-911,912-1051",NaN,1

In [13]:
# This cell took about 6 minutes to run
for uniprotID in lambert_TFs["uniprotID"]:
    output_file = f"../data/lambert_TF_AF/{uniprotID}.pdb"
    download_alphafold_pdb(uniprotID, output_path=output_file)

Fetching AlphaFold structure for UniProt ID: A0A087WUV0
✅ Download complete: ../data/lambert_TF_AF/A0A087WUV0.pdb
Fetching AlphaFold structure for UniProt ID: A0AVK6
✅ Download complete: ../data/lambert_TF_AF/A0AVK6.pdb
Fetching AlphaFold structure for UniProt ID: A0PJY2
✅ Download complete: ../data/lambert_TF_AF/A0PJY2.pdb
Fetching AlphaFold structure for UniProt ID: A1A519
✅ Download complete: ../data/lambert_TF_AF/A1A519.pdb
Fetching AlphaFold structure for UniProt ID: A1YPR0
✅ Download complete: ../data/lambert_TF_AF/A1YPR0.pdb
Fetching AlphaFold structure for UniProt ID: A2RRD8
✅ Download complete: ../data/lambert_TF_AF/A2RRD8.pdb
Fetching AlphaFold structure for UniProt ID: A2RU54
✅ Download complete: ../data/lambert_TF_AF/A2RU54.pdb
Fetching AlphaFold structure for UniProt ID: A4D1E1
✅ Download complete: ../data/lambert_TF_AF/A4D1E1.pdb
Fetching AlphaFold structure for UniProt ID: A6NCS4
✅ Download complete: ../data/lambert_TF_AF/A6NCS4.pdb
Fetching AlphaFold structure for UniProt ID: A6NFD8
✅ Download complete: ../data/lambert_TF_AF/A6NFD8.pdb
Fetching AlphaFold structure for UniProt ID: A6NFI3
✅ Download complete: ../data/lambert_TF_AF/A6NFI3.pdb
Fetching AlphaFold structure for UniProt ID: A6NFQ7
✅ Download complete: ../data/lambert_TF_AF/A6NFQ7.pdb
Fetching AlphaFold structure for UniProt ID: A6NGD5
✅ Download complete: ../data/lambert_TF_AF/A6NGD5.pdb
Fetching AlphaFold structure for UniProt ID: A6NHJ4
✅ Download complete: ../data/lambert_TF_AF/A6NHJ4.pdb
Fetching AlphaFold structure for UniProt ID: A6NHT5
✅ Download complete: ../data/lambert_TF_AF/A6NHT5.pdb
Fetching AlphaFold structure for UniProt ID: A6NI15
✅ Download complete: ../data/lambert_TF_AF/A6NI15.pdb
Fetching AlphaFold structure for UniProt ID: A6NJ46
✅ Download complete: ../data/lambert_TF_AF/A6NJ46.pdb
Fetching AlphaFold structure for UniProt ID: A6NJG6
✅ Download complete: ../data/lambert_TF_AF/A6NJG6.pdb
Fetching AlphaFold structure for UniProt ID: A6NJL1
✅ Download complete: ../data/lambert_TF_AF/A6NJL1.pdb
Fetching AlphaFold structure for UniProt ID: A6NJT0
✅ Download complete: ../data/lambert_TF_AF/A6NJT0.pdb
Fetching AlphaFold structure for UniProt ID: A6NK53
✅ Download complete: ../data/lambert_TF_AF/A6NK53.pdb
Fetching AlphaFold structure for UniProt ID: A6NK75
✅ Download complete: ../data/lambert_TF_AF/A6NK75.pdb
Fetching AlphaFold structure for UniProt ID: A6NKF2
✅ Download complete: ../data/lambert_TF_AF/A6NKF2.pdb
Fetching AlphaFold structure for UniProt ID: A6NLW8
✅ Download complete: ../data/lambert_TF_AF/A6NLW8.pdb
Fetching AlphaFold structure for UniProt ID: A6NM28
✅ Download complete: ../data/lambert_TF_AF/A6NM28.pdb
Fetching AlphaFold structure for UniProt ID: A6NMT0
✅ Download complete: ../data/lambert_TF_AF/A6NMT0.pdb
Fetching AlphaFold structure for UniProt ID: A6NN14
✅ Download complete: ../data/lambert_TF_AF/A6NN14.pdb
Fetching AlphaFold structure for UniProt ID: A6NNA5
✅ Download complete: ../data/lambert_TF_AF/A6NNA5.pdb
Fetching AlphaFold structure for UniProt ID: A6NNF4
✅ Download complete: ../data/lambert_TF_AF/A6NNF4.pdb
Fetching AlphaFold structure for UniProt ID: A6NP11
✅ Download complete: ../data/lambert_TF_AF/A6NP11.pdb
Fetching AlphaFold structure for UniProt ID: A8K8V0
✅ Download complete: ../data/lambert_TF_AF/A8K8V0.pdb
Fetching AlphaFold structure for UniProt ID: A8MQ14
✅ Download complete: ../data/lambert_TF_AF/A8MQ14.pdb
Fetching AlphaFold structure for UniProt ID: A8MT65
✅ Download complete: ../data/lambert_TF_AF/A8MT65.pdb
Fetching AlphaFold structure for UniProt ID: A8MT69
✅ Download complete: ../data/lambert_TF_AF/A8MT69.pdb
Fetching AlphaFold structure for UniProt ID: A8MTJ6
✅ Download complete: ../data/lambert_TF_AF/A8MTJ6.pdb
Fetching AlphaFold structure for UniProt ID: A8MTQ0
✅ Download complete: ../data/lambert_TF_AF/A8MTQ0.pdb
Fetching AlphaFold structure for UniProt ID: A8MTY0
✅ Download complete: ../data/lambert_TF_AF/A8MTY0.pdb
Fetching AlphaFold structure for UniProt ID: A8MUV8
✅ Download complete: ../data/lambert_TF_AF/A8MUV8.pdb
Fetching AlphaFold structure for UniProt ID: A8MUZ8
✅ Download complete: ../data/lambert_TF_AF/A8MUZ8.pdb
Fetching AlphaFold structure for UniProt ID: A8MXY4
✅ Download complete: ../data/lambert_TF_AF/A8MXY4.pdb
Fetching AlphaFold structure for UniProt ID: A8MYZ6
✅ Download complete: ../data/lambert_TF_AF/A8MYZ6.pdb
Fetching AlphaFold structure for UniProt ID: A8MZ59
✅ Download complete: ../data/lambert_TF_AF/A8MZ59.pdb
Fetching AlphaFold structure for UniProt ID: B1APH4
✅ Download complete: ../data/lambert_TF_AF/B1APH4.pdb
Fetching AlphaFold structure for UniProt ID: B2RXF5
✅ Download complete: ../data/lambert_TF_AF/B2RXF5.pdb
Fetching AlphaFold structure for UniProt ID: B4DU55
✅ Download complete: ../data/lambert_TF_AF/B4DU55.pdb
Fetching AlphaFold structure for UniProt ID: B4DX44
✅ Download complete: ../data/lambert_TF_AF/B4DX44.pdb
Fetching AlphaFold structure for UniProt ID: B4DXR9
✅ Download complete: ../data/lambert_TF_AF/B4DXR9.pdb
Fetching AlphaFold structure for UniProt ID: B7Z6K7
✅ Download complete: ../data/lambert_TF_AF/B7Z6K7.pdb
Fetching AlphaFold structure for UniProt ID: C9JLR9
✅ Download complete: ../data/lambert_TF_AF/C9JLR9.pdb
Fetching AlphaFold structure for UniProt ID: C9JN71
✅ Download complete: ../data/lambert_TF_AF/C9JN71.pdb
Fetching AlphaFold structure for UniProt ID: E7ETH6
✅ Download complete: ../data/lambert_TF_AF/E7ETH6.pdb
Fetching AlphaFold structure for UniProt ID: E9PGG2
✅ Download complete: ../data/lambert_TF_AF/E9PGG2.pdb
Fetching AlphaFold structure for UniProt ID: O00110
✅ Download complete: ../data/lambert_TF_AF/O00110.pdb
Fetching AlphaFold structure for UniProt ID: O00321
✅ Download complete: ../data/lambert_TF_AF/O00321.pdb
Fetching AlphaFold structure for UniProt ID: O00327
✅ Download complete: ../data/lambert_TF_AF/O00327.pdb
Fetching AlphaFold structure for UniProt ID: O00358
✅ Download complete: ../data/lambert_TF_AF/O00358.pdb
Fetching AlphaFold structure for UniProt ID: O00409
✅ Download complete: ../data/lambert_TF_AF/O00409.pdb
Fetching AlphaFold structure for UniProt ID: O00470
✅ Download complete: ../data/lambert_TF_AF/O00470.pdb
Fetching AlphaFold structure for UniProt ID: O00482
✅ Download complete: ../data/lambert_TF_AF/O00482.pdb
Fetching AlphaFold structure for UniProt ID: O00570
✅ Download complete: ../data/lambert_TF_AF/O00570.pdb
Fetching AlphaFold structure for UniProt ID: O00712
✅ Download complete: ../data/lambert_TF_AF/O00712.pdb
Fetching AlphaFold structure for UniProt ID: O00716
✅ Download complete: ../data/lambert_TF_AF/O00716.pdb
Fetching AlphaFold structure for UniProt ID: O14503
✅ Download complete: ../data/lambert_TF_AF/O14503.pdb
Fetching AlphaFold structure for UniProt ID: O14529
✅ Download complete: ../data/lambert_TF_AF/O14529.pdb
Fetching AlphaFold structure for UniProt ID: O14545
✅ Download complete: ../data/lambert_TF_AF/O14545.pdb
Fetching AlphaFold structure for UniProt ID: O14627
✅ Download complete: ../data/lambert_TF_AF/O14627.pdb
Fetching AlphaFold structure for UniProt ID: O14628
✅ Download complete: ../data/lambert_TF_AF/O14628.pdb
Fetching AlphaFold structure for UniProt ID: O14709
✅ Download complete: ../data/lambert_TF_AF/O14709.pdb
Fetching AlphaFold structure for UniProt ID: O14753
✅ Download complete: ../data/lambert_TF_AF/O14753.pdb
Fetching AlphaFold structure for UniProt ID: O14770
✅ Download complete: ../data/lambert_TF_AF/O14770.pdb
Fetching AlphaFold structure for UniProt ID: O14771
✅ Download complete: ../data/lambert_TF_AF/O14771.pdb
Fetching AlphaFold structure for UniProt ID: O14813
✅ Download complete: ../data/lambert_TF_AF/O14813.pdb
Fetching AlphaFold structure for UniProt ID: O14867
✅ Download complete: ../data/lambert_TF_AF/O14867.pdb
Fetching AlphaFold structure for UniProt ID: O14896
✅ Download complete: ../data/lambert_TF_AF/O14896.pdb
Fetching AlphaFold structure for UniProt ID: O14901
✅ Download complete: ../data/lambert_TF_AF/O14901.pdb
Fetching AlphaFold structure for UniProt ID: O14948
✅ Download complete: ../data/lambert_TF_AF/O14948.pdb
Fetching AlphaFold structure for UniProt ID: O14978
✅ Download complete: ../data/lambert_TF_AF/O14978.pdb
Fetching AlphaFold structure for UniProt ID: O15014
✅ Download complete: ../data/lambert_TF_AF/O15014.pdb
Fetching AlphaFold structure for UniProt ID: O15015
✅ Download complete: ../data/lambert_TF_AF/O15015.pdb
Fetching AlphaFold structure for UniProt ID: O15060
✅ Download complete: ../data/lambert_TF_AF/O15060.pdb
Fetching AlphaFold structure for UniProt ID: O15062
✅ Download complete: ../data/lambert_TF_AF/O15062.pdb
Fetching AlphaFold structure for UniProt ID: O15090
✅ Download complete: ../data/lambert_TF_AF/O15090.pdb
Fetching AlphaFold structure for UniProt ID: O15119
✅ Download complete: ../data/lambert_TF_AF/O15119.pdb
Fetching AlphaFold structure for UniProt ID: O15156
✅ Download complete: ../data/lambert_TF_AF/O15156.pdb
Fetching AlphaFold structure for UniProt ID: O15162
✅ Download complete: ../data/lambert_TF_AF/O15162.pdb
Fetching AlphaFold structure for UniProt ID: O15178
✅ Download complete: ../data/lambert_TF_AF/O15178.pdb
Fetching AlphaFold structure for UniProt ID: O15198
✅ Download complete: ../data/lambert_TF_AF/O15198.pdb
Fetching AlphaFold structure for UniProt ID: O15209
✅ Download complete: ../data/lambert_TF_AF/O15209.pdb
Fetching AlphaFold structure for UniProt ID: O15226
✅ Download complete: ../data/lambert_TF_AF/O15226.pdb
Fetching AlphaFold structure for UniProt ID: O15266
✅ Download complete: ../data/lambert_TF_AF/O15266.pdb
Fetching AlphaFold structure for UniProt ID: O15350
✅ Download complete: ../data/lambert_TF_AF/O15350.pdb
Fetching AlphaFold structure for UniProt ID: O15353
✅ Download complete: ../data/lambert_TF_AF/O15353.pdb
Fetching AlphaFold structure for UniProt ID: O15370
✅ Download complete: ../data/lambert_TF_AF/O15370.pdb
Fetching AlphaFold structure for UniProt ID: O15391
✅ Download complete: ../data/lambert_TF_AF/O15391.pdb
Fetching AlphaFold structure for UniProt ID: O15409
✅ Download complete: ../data/lambert_TF_AF/O15409.pdb
Fetching AlphaFold structure for UniProt ID: O15499
✅ Download complete: ../data/lambert_TF_AF/O15499.pdb
Fetching AlphaFold structure for UniProt ID: O15516
✅ Download complete: ../data/lambert_TF_AF/O15516.pdb
Fetching AlphaFold structure for UniProt ID: O15522
✅ Download complete: ../data/lambert_TF_AF/O15522.pdb
Fetching AlphaFold structure for UniProt ID: O15525
✅ Download complete: ../data/lambert_TF_AF/O15525.pdb
Fetching AlphaFold structure for UniProt ID: O15535
✅ Download complete: ../data/lambert_TF_AF/O15535.pdb
Fetching AlphaFold structure for UniProt ID: O43147
✅ Download complete: ../data/lambert_TF_AF/O43147.pdb
Fetching AlphaFold structure for UniProt ID: O43151
✅ Download complete: ../data/lambert_TF_AF/O43151.pdb
Fetching AlphaFold structure for UniProt ID: O43167
✅ Download complete: ../data/lambert_TF_AF/O43167.pdb
Fetching AlphaFold structure for UniProt ID: O43186
✅ Download complete: ../data/lambert_TF_AF/O43186.pdb
Fetching AlphaFold structure for UniProt ID: O43189
✅ Download complete: ../data/lambert_TF_AF/O43189.pdb
Fetching AlphaFold structure for UniProt ID: O43248
✅ Download complete: ../data/lambert_TF_AF/O43248.pdb
Fetching AlphaFold structure for UniProt ID: O43296
✅ Download complete: ../data/lambert_TF_AF/O43296.pdb
Fetching AlphaFold structure for UniProt ID: O43298
✅ Download complete: ../data/lambert_TF_AF/O43298.pdb
Fetching AlphaFold structure for UniProt ID: O43309
✅ Download complete: ../data/lambert_TF_AF/O43309.pdb
Fetching AlphaFold structure for UniProt ID: O43313
✅ Download complete: ../data/lambert_TF_AF/O43313.pdb
Fetching AlphaFold structure for UniProt ID: O43316
✅ Download complete: ../data/lambert_TF_AF/O43316.pdb
Fetching AlphaFold structure for UniProt ID: O43345
✅ Download complete: ../data/lambert_TF_AF/O43345.pdb
Fetching AlphaFold structure for UniProt ID: O43361
✅ Download complete: ../data/lambert_TF_AF/O43361.pdb
Fetching AlphaFold structure for UniProt ID: O43364
✅ Download complete: ../data/lambert_TF_AF/O43364.pdb
Fetching AlphaFold structure for UniProt ID: O43365
✅ Download complete: ../data/lambert_TF_AF/O43365.pdb
Fetching AlphaFold structure for UniProt ID: O43422
✅ Download complete: ../data/lambert_TF_AF/O43422.pdb
Fetching AlphaFold structure for UniProt ID: O43435
✅ Download complete: ../data/lambert_TF_AF/O43435.pdb
Fetching AlphaFold structure for UniProt ID: O43474
✅ Download complete: ../data/lambert_TF_AF/O43474.pdb
Fetching AlphaFold structure for UniProt ID: O43524
✅ Download complete: ../data/lambert_TF_AF/O43524.pdb
Fetching AlphaFold structure for UniProt ID: O43623
✅ Download complete: ../data/lambert_TF_AF/O43623.pdb
Fetching AlphaFold structure for UniProt ID: O43638
✅ Download complete: ../data/lambert_TF_AF/O43638.pdb
Fetching AlphaFold structure for UniProt ID: O43670
✅ Download complete: ../data/lambert_TF_AF/O43670.pdb
Fetching AlphaFold structure for UniProt ID: O43680
✅ Download complete: ../data/lambert_TF_AF/O43680.pdb
Fetching AlphaFold structure for UniProt ID: O43711
✅ Download complete: ../data/lambert_TF_AF/O43711.pdb
Fetching AlphaFold structure for UniProt ID: O43763
✅ Download complete: ../data/lambert_TF_AF/O43763.pdb
Fetching AlphaFold structure for UniProt ID: O43823
✅ Download complete: ../data/lambert_TF_AF/O43823.pdb
Fetching AlphaFold structure for UniProt ID: O43829
✅ Download complete: ../data/lambert_TF_AF/O43829.pdb
Fetching AlphaFold structure for UniProt ID: O43889
✅ Download complete: ../data/lambert_TF_AF/O43889.pdb
Fetching AlphaFold structure for UniProt ID: O43918
✅ Download complete: ../data/lambert_TF_AF/O43918.pdb
Fetching AlphaFold structure for UniProt ID: O60248
✅ Download complete: ../data/lambert_TF_AF/O60248.pdb
Fetching AlphaFold structure for UniProt ID: O60281
❌ HTTP error occurred: 404 Client Error: Not Found for url: https://alphafold.ebi.ac.uk/files/AF-O60281-F1-model_v4.pdb
Fetching AlphaFold structure for UniProt ID: O60284
✅ Download complete: ../data/lambert_TF_AF/O60284.pdb
Fetching AlphaFold structure for UniProt ID: O60304
✅ Download complete: ../data/lambert_TF_AF/O60304.pdb
Fetching AlphaFold structure for UniProt ID: O60315
✅ Download complete: ../data/lambert_TF_AF/O60315.pdb
Fetching AlphaFold structure for UniProt ID: O60381
✅ Download complete: ../data/lambert_TF_AF/O60381.pdb
Fetching AlphaFold structure for UniProt ID: O60393
✅ Download complete: ../data/lambert_TF_AF/O60393.pdb
Fetching AlphaFold structure for UniProt ID: O60422
✅ Download complete: ../data/lambert_TF_AF/O60422.pdb
Fetching AlphaFold structure for UniProt ID: O60479
✅ Download complete: ../data/lambert_TF_AF/O60479.pdb
Fetching AlphaFold structure for UniProt ID: O60481
✅ Download complete: ../data/lambert_TF_AF/O60481.pdb
Fetching AlphaFold structure for UniProt ID: O60519
✅ Download complete: ../data/lambert_TF_AF/O60519.pdb
Fetching AlphaFold structure for UniProt ID: O60548
✅ Download complete: ../data/lambert_TF_AF/O60548.pdb
Fetching AlphaFold structure for UniProt ID: O60663
✅ Download complete: ../data/lambert_TF_AF/O60663.pdb
Fetching AlphaFold structure for UniProt ID: O60675
✅ Download complete: ../data/lambert_TF_AF/O60675.pdb
Fetching AlphaFold structure for UniProt ID: O60678
✅ Download complete: ../data/lambert_TF_AF/O60678.pdb
Fetching AlphaFold structure for UniProt ID: O60682
✅ Download complete: ../data/lambert_TF_AF/O60682.pdb
Fetching AlphaFold structure for UniProt ID: O60765
✅ Download complete: ../data/lambert_TF_AF/O60765.pdb
Fetching AlphaFold structure for UniProt ID: O60806
✅ Download complete: ../data/lambert_TF_AF/O60806.pdb
Fetching AlphaFold structure for UniProt ID: O60870
✅ Download complete: ../data/lambert_TF_AF/O60870.pdb
Fetching AlphaFold structure for UniProt ID: O60902
✅ Download complete: ../data/lambert_TF_AF/O60902.pdb
Fetching AlphaFold structure for UniProt ID: O75030
✅ Download complete: ../data/lambert_TF_AF/O75030.pdb
Fetching AlphaFold structure for UniProt ID: O75123
✅ Download complete: ../data/lambert_TF_AF/O75123.pdb
Fetching AlphaFold structure for UniProt ID: O75132
✅ Download complete: ../data/lambert_TF_AF/O75132.pdb
Fetching AlphaFold structure for UniProt ID: O75290
✅ Download complete: ../data/lambert_TF_AF/O75290.pdb
Fetching AlphaFold structure for UniProt ID: O75333
✅ Download complete: ../data/lambert_TF_AF/O75333.pdb
Fetching AlphaFold structure for UniProt ID: O75346
✅ Download complete: ../data/lambert_TF_AF/O75346.pdb
Fetching AlphaFold structure for UniProt ID: O75360
✅ Download complete: ../data/lambert_TF_AF/O75360.pdb
Fetching AlphaFold structure for UniProt ID: O75362
✅ Download complete: ../data/lambert_TF_AF/O75362.pdb
Fetching AlphaFold structure for UniProt ID: O75364
✅ Download complete: ../data/lambert_TF_AF/O75364.pdb
Fetching AlphaFold structure for UniProt ID: O75373
✅ Download complete: ../data/lambert_TF_AF/O75373.pdb
Fetching AlphaFold structure for UniProt ID: O75398
✅ Download complete: ../data/lambert_TF_AF/O75398.pdb
Fetching AlphaFold structure for UniProt ID: O75437
✅ Download complete: ../data/lambert_TF_AF/O75437.pdb
Fetching AlphaFold structure for UniProt ID: O75444
✅ Download complete: ../data/lambert_TF_AF/O75444.pdb
Fetching AlphaFold structure for UniProt ID: O75461
✅ Download complete: ../data/lambert_TF_AF/O75461.pdb
Fetching AlphaFold structure for UniProt ID: O75467
✅ Download complete: ../data/lambert_TF_AF/O75467.pdb
Fetching AlphaFold structure for UniProt ID: O75469
✅ Download complete: ../data/lambert_TF_AF/O75469.pdb
Fetching AlphaFold structure for UniProt ID: O75541
✅ Download complete: ../data/lambert_TF_AF/O75541.pdb
Fetching AlphaFold structure for UniProt ID: O75564
✅ Download complete: ../data/lambert_TF_AF/O75564.pdb
Fetching AlphaFold structure for UniProt ID: O75593
✅ Download complete: ../data/lambert_TF_AF/O75593.pdb
Fetching AlphaFold structure for UniProt ID: O75603
✅ Download complete: ../data/lambert_TF_AF/O75603.pdb
Fetching AlphaFold structure for UniProt ID: O75626
✅ Download complete: ../data/lambert_TF_AF/O75626.pdb
Fetching AlphaFold structure for UniProt ID: O75820
✅ Download complete: ../data/lambert_TF_AF/O75820.pdb
Fetching AlphaFold structure for UniProt ID: O75840
✅ Download complete: ../data/lambert_TF_AF/O75840.pdb
Fetching AlphaFold structure for UniProt ID: O75971
✅ Download complete: ../data/lambert_TF_AF/O75971.pdb
Fetching AlphaFold structure for UniProt ID: O94892
✅ Download complete: ../data/lambert_TF_AF/O94892.pdb
Fetching AlphaFold structure for UniProt ID: O94916
✅ Download complete: ../data/lambert_TF_AF/O94916.pdb
Fetching AlphaFold structure for UniProt ID: O94983
✅ Download complete: ../data/lambert_TF_AF/O94983.pdb
Fetching AlphaFold structure for UniProt ID: O94993
✅ Download complete: ../data/lambert_TF_AF/O94993.pdb
Fetching AlphaFold structure for UniProt ID: O95076
✅ Download complete: ../data/lambert_TF_AF/O95076.pdb
Fetching AlphaFold structure for UniProt ID: O95096
✅ Download complete: ../data/lambert_TF_AF/O95096.pdb
Fetching AlphaFold structure for UniProt ID: O95125
✅ Download complete: ../data/lambert_TF_AF/O95125.pdb
Fetching AlphaFold structure for UniProt ID: O95201
✅ Download complete: ../data/lambert_TF_AF/O95201.pdb
Fetching AlphaFold structure for UniProt ID: O95231
✅ Download complete: ../data/lambert_TF_AF/O95231.pdb
Fetching AlphaFold structure for UniProt ID: O95238
✅ Download complete: ../data/lambert_TF_AF/O95238.pdb
Fetching AlphaFold structure for UniProt ID: O95243
✅ Download complete: ../data/lambert_TF_AF/O95243.pdb
Fetching AlphaFold structure for UniProt ID: O95251
✅ Download complete: ../data/lambert_TF_AF/O95251.pdb
Fetching AlphaFold structure for UniProt ID: O95343
✅ Download complete: ../data/lambert_TF_AF/O95343.pdb
Fetching AlphaFold structure for UniProt ID: O95365
✅ Download complete: ../data/lambert_TF_AF/O95365.pdb
Fetching AlphaFold structure for UniProt ID: O95409

# 2. Running DSSP

In [ ]:
# G 3-turn helix (3_10 helix)
# H 4-turn helix (alpha-helix)
# I 5-turn helix (pi helix)

# E extended strand in parallel and/or anti-parallel β-sheet conformation. Min length 2 residues
# B residue in isolated β-bridge (single pair β-sheet hydrogen bond formation)

# P Polyproline

# T H-bonded turn
# S bend

# - coil -- ignore

In [34]:
from concurrent.futures import ProcessPoolExecutor

In [55]:
def parse_pdb(path):
    try:
        uniprotID = path.split("/")[-1].split(".")[0]
        p = PDBParser()
        structure = p.get_structure(uniprotID, path)
        model = structure[0]
        dssp = DSSP(model, path)
        pos = []
        code = []
        
        keys = list(dssp.keys())
        for i in range(len(keys)):
            pos.append(i)
            a_key = keys[i]
            code.append(dssp[a_key][2])

        codes = pd.DataFrame({"pos" : pos, "code" : code})
        codes["uniprotID"] = uniprotID
        return codes
    except Exception as e: 
        print(f"Error parsing {uniprotID}: {e}")

In [56]:
parse_pdb("../data/lambert_TF_AF/P11308.pdb")

     pos code uniprotID
0      0    -    P11308
1      1    -    P11308
2      2    -    P11308
3      3    -    P11308
4      4    -    P11308
..   ...  ...       ...
474  474    -    P11308
475  475    -    P11308
476  476    -    P11308
477  477    -    P11308
478  478    -    P11308

[479 rows x 3 columns]

In [57]:
from concurrent.futures import ThreadPoolExecutor

paths = glob.glob("../data/lambert_TF_AF/*")

with ThreadPoolExecutor() as executor:
    dssp_dfs = list(executor.map(parse_pdb, paths))

/opt/anaconda3/lib/python3.12/site-packages/Bio/PDB/DSSP.py:199: UserWarning: Trying to parse 'HUMA'
Error parsing PDB at line 38
Not a valid integer in PDB record

  warnings.warn(err)

Error parsing A0A087WUV0: DSSP failed to produce an output

In [58]:
dssp_df = pd.concat(dssp_dfs)
dssp_df

     pos code uniprotID
0      0    -    Q9NZC4
1      1    -    Q9NZC4
2      2    -    Q9NZC4
3      3    -    Q9NZC4
4      4    -    Q9NZC4
..   ...  ...       ...
454  454    S    Q8TBJ5
455  455    S    Q8TBJ5
456  456    S    Q8TBJ5
457  457    -    Q8TBJ5
458  458    -    Q8TBJ5

[907797 rows x 3 columns]

In [59]:
dssp_df.to_csv("../output/lambert_TF_AF_dssp.csv")

In [60]:
len(set(dssp_df["uniprotID"]))

1600