In [1]:
import pandas as pd

In [9]:
trunc_diff_loc = pd.read_excel("../data/isoform_localization_media-1.xlsx", sheet_name = "Differential_trunc_anno")
trunc_diff_loc["gene"] = trunc_diff_loc["Chromosome_position_strand_GeneID_StartCodon_ORFtype"].str.split("_").str[3]
trunc_diff_loc

,GeneID,Chromosome_position_strand_GeneID_StartCodon_ORFtype,Predicted Localization Annotated isoform,Chromosome_position_strand_GeneID_StartCodon_ORFtype.1,Predicted Localization Truncated isoform,gene
0,ENSG00000154556.17,chr4_185690571_-_SORBS2_ENSG00000154556.17_AUG...,Cell,chr4_185611806_-_SORBS2_ENSG00000154556.17_AGG...,Cytoplasm,SORBS2
1,ENSG00000169398.19,chr8_140890737_-_PTK2_ENSG00000169398.19_AUG_A...,Cell,chr8_140890662_-_PTK2_ENSG00000169398.19_AUG_T...,Cytoplasm,PTK2
2,ENSG00000196814.14,chr9_126326929_+_MVB12B_ENSG00000196814.14_AUG...,Cell,chr9_126340519_+_MVB12B_ENSG00000196814.14_AUG...,Cytoplasm,MVB12B
3,ENSG00000087460.23,chr20_58891726_+_GNAS_ENSG00000087460.23_AUG_A...,Cell,chr20_58905400_+_GNAS_ENSG00000087460.23_AAG_T...,Cytoplasm,GNAS
4,ENSG00000073712.14,chr14_52950568_-_FERMT2_ENSG00000073712.14_AUG...,Cell,chr14_52864794_-_FERMT2_ENSG00000073712.14_AUU...,Cytoplasm,FERMT2
...,...,...,...,...,...,...
330,ENSG00000133835.14,chr5_119452575_+_HSD17B4_ENSG00000133835.14_AU...,Peroxisome,chr5_119509157_+_HSD17B4_ENSG00000133835.14_AA...,Cytoplasm,HSD17B4
331,ENSG00000148803.11,chr10_133357995_-_FUOM_ENSG00000148803.11_AAG_...,Peroxisome,chr10_133357944_-_FUOM_ENSG00000148803.11_AUG_...,Cytoplasm,FUOM
332,ENSG00000099968.17,chr22_17655711_+_BCL2L13_ENSG00000099968.17_AU...,Peroxisome,chr22_17638864_+_BCL2L13_ENSG00000099968.17_CU...,Mitochondrion,BCL2L13
333,ENSG00000137409.19,chr6_36986173_-_MTCH1_ENSG00000137409.19_AUG_A...,Peroxisome,chr6_36986119_-_MTCH1_ENSG00000137409.19_AUG_T...,Mitochondrion,MTCH1
334,ENSG00000109919.9,chr11_47642465_-_MTCH2_ENSG00000109919.9_AUG_A...,Peroxisome,chr11_47642417_-_MTCH2_ENSG00000109919.9_CUG_T...,Mitochondrion,MTCH2

In [10]:
exten_diff_loc = pd.read_excel("../data/isoform_localization_media-1.xlsx", sheet_name = "Differential_extension_anno")
exten_diff_loc["gene"] = exten_diff_loc["Chromosome_position_strand_GeneID_StartCodon_ORFtype"].str.split("_").str[3]
exten_diff_loc

,GeneID,Chromosome_position_strand_GeneID_StartCodon_ORFtype,Predicted Localization Annotated isoform,Chromosome_position_strand_GeneID_StartCodon_ORFtype.1,Predicted Localization Extended isoform,gene
0,ENSG00000075651.15,chr3_171738051_-_PLD1_ENSG00000075651.15_AUG_A...,Cell,chr3_171810424_-_PLD1_ENSG00000075651.15_GUG_E...,Cytoplasm,PLD1
1,ENSG00000134108.12,chr3_5122465_+_ARL8B_ENSG00000134108.12_AUG_An...,Cell,chr3_5122402_+_ARL8B_ENSG00000134108.12_GUG_Ex...,Cytoplasm,ARL8B
2,ENSG00000154556.17,chr4_185690571_-_SORBS2_ENSG00000154556.17_AUG...,Cell,chr4_185775258_-_SORBS2_ENSG00000154556.17_AUA...,Cytoplasm,SORBS2
3,ENSG00000169398.19,chr8_140890737_-_PTK2_ENSG00000169398.19_AUG_A...,Cell,chr8_141001146_-_PTK2_ENSG00000169398.19_ACG_E...,Cytoplasm,PTK2
4,ENSG00000072415.8,chr14_67279170_+_MPP5_ENSG00000072415.8_AUG_An...,Cell,chr14_67241469_+_MPP5_ENSG00000072415.8_CUG_Ex...,Cytoplasm,MPP5
...,...,...,...,...,...,...
246,ENSG00000142039.3,chr19_41310310_+_CCDC97_ENSG00000142039.3_AUG_...,Nucleus,chr19_41310235_+_CCDC97_ENSG00000142039.3_GUG_...,Mitochondrion,CCDC97
247,ENSG00000188690.12,chr10_125816499_-_UROS_ENSG00000188690.12_AUG_...,Nucleus,chr10_125823104_-_UROS_ENSG00000188690.12_CUG_...,Mitochondrion,UROS
248,ENSG00000176055.9,chr5_90474292_-_MBLAC2_ENSG00000176055.9_AUG_A...,Peroxisome,chr5_90474400_-_MBLAC2_ENSG00000176055.9_CUG_E...,Cytoplasm,MBLAC2
249,ENSG00000112874.9,chr5_103560248_-_NUDT12_ENSG00000112874.9_AUG_...,Peroxisome,chr5_103562738_-_NUDT12_ENSG00000112874.9_CUG_...,Cytoplasm,NUDT12
250,ENSG00000109919.9,chr11_47642465_-_MTCH2_ENSG00000109919.9_AUG_A...,Peroxisome,chr11_47642468_-_MTCH2_ENSG00000109919.9_AUC_E...,Mitochondrion,MTCH2

# Are known ADs on any of these genes? - unsure how many are TFs

In [11]:
known_ADs = pd.read_csv("../output/known_ADs_considering_isoforms_and_canonical_with_alerasool.csv")
known_ADs

,Unnamed: 0,Gene,Start,End,uniprotID,Matching Isoforms,Canonical Transcript ID,orig_uniprotID,Reference,TileType,ProteinRegionSeq
0,0,ABRAXAS1,121,200,Q6UWZ7,[['Q6UWZ7']],ENST00000321945,Q6UWZ7,"DelRosso et al. (Q6UWZ7, 121_200)",CR,LQEHFSNQDLVFLLLTPSIITESCSTHRLEHSLYKPQKGLFHRVPL...
1,1,AHR,118,126,P35869,[['P35869']],NaN,P35869,"transcriptionalactivity_regions.txt, GSL (P358...",TF,LLQALNGFV
2,2,AHR,266,268,P35869,[['P35869']],NaN,P35869,"transcriptionalactivity_regions.txt, GSL (P358...",TF,FAI
3,3,AHR,532,848,P35869,"[['P35869'], ['P35869'], ['P35869']]",ENST00000242057 / nan / ENST00000242057,P35869 / P35869 / P35869,"DelRosso et al. (P35869, 532_641) // PMID: 879...",TF / TF / TF,QDSKNSDLYSIMKNLGIDFEDIRHMQNEKFFRNDFSGEVDFRDIDL...
4,4,AKAP8,2,81,O43823,[['O43823']],ENST00000269701,O43823,"DelRosso et al. (O43823, 2_81)",TF,DQGYGGYGAWSAGPANTQGAYGTGVASWQGYENYNYYGAQNTSVTT...
...,...,...,...,...,...,...,...,...,...,...,...
756,757,ATXN7L3,1,120,Q14CW9,"[['Q14CW9', 'Q14CW9-2']]",NaN,NaN,Alerasool et al,TF,MKMEEMSLSGLDNSKLEAIAQEIYADLVEDSCLGFCFEVHRAVKCG...
757,758,FAM22F,361,500,A1L443,[['A1L443']],NaN,NaN,Alerasool et al,TF,PRPQRPAETNAHLPPPRPQRPAETKVPEEIPPEVVQEYVDIMEELL...
758,759,SS18L2,18,77,Q9UHA2,[['Q9UHA2']],NaN,NaN,Alerasool et al,TF,QETIQRLLEENDQLIRCIVEYQNKGRGNECVQYQHVLHRNLIYLAT...
759,760,SERTAD2,201,260,Q14140,[['Q14140']],NaN,NaN,Alerasool et al,TF,SEAGTQKLDGPQESRADDSKLMDSLPGNFEITTSTGFLTDLTLDDI...
760,761,BTBD18,461,540,B2RXH4,[['B2RXH4']],NaN,NaN,Alerasool et al,TF,IDCREPYAFDTALLEQPCEAEEYRITSAAATSELEEILDFMLCGSD...

In [15]:
known_ADs[known_ADs["Gene"].isin(trunc_diff_loc["gene"])]

,Unnamed: 0,Gene,Start,End,uniprotID,Matching Isoforms,Canonical Transcript ID,orig_uniprotID,Reference,TileType,ProteinRegionSeq
495,496,IRF3,134,427,Q14653,[['Q14653']],NaN,Q14653,"PMID: 10082512, Soto (Q14653, 134_427)",TF,DTQEDILDELLGNMVLAPLPDPGPPSLAVAPEPCPQPLRSPSLDNP...

In [14]:
trunc_diff_loc[trunc_diff_loc["gene"].isin(known_ADs["Gene"])]

,GeneID,Chromosome_position_strand_GeneID_StartCodon_ORFtype,Predicted Localization Annotated isoform,Chromosome_position_strand_GeneID_StartCodon_ORFtype.1,Predicted Localization Truncated isoform,gene
328,ENSG00000126456.15,chr19_49664838_-_IRF3_ENSG00000126456.15_AUG_A...,Nucleus,chr19_49663216_-_IRF3_ENSG00000126456.15_AUG_T...,Mitochondrion,IRF3

In [17]:
known_ADs[known_ADs["Gene"].isin(exten_diff_loc["gene"])]

,Unnamed: 0,Gene,Start,End,uniprotID,Matching Isoforms,Canonical Transcript ID,orig_uniprotID,Reference,TileType,ProteinRegionSeq
744,745,CITED2,201,270,Q99967,"[['Q99967'], ['Q99967']]",nan / nan,nan / Q99967 / Q99967,Alerasool et al // MVS fragment / Berlow et al...,TF / TF,MPASVAHVPAAMLPPNVIDTDFIDEEVLMSLVIEMGLDRIKELPEL...

In [18]:
exten_diff_loc[exten_diff_loc["gene"].isin(known_ADs["Gene"])]

,GeneID,Chromosome_position_strand_GeneID_StartCodon_ORFtype,Predicted Localization Annotated isoform,Chromosome_position_strand_GeneID_StartCodon_ORFtype.1,Predicted Localization Extended isoform,gene
76,ENSG00000164442.9,chr6_139373944_-_CITED2_ENSG00000164442.9_AUG_...,Cytoplasm,chr6_139374617_-_CITED2_ENSG00000164442.9_CUG_...,Nucleus,CITED2

known_ADsa