In [1]:
import pandas as pd

In [7]:
soto = pd.read_excel("../data/Soto_supplemental_table", sheet_name = "Table S2")
soto_RDs = soto[soto["Domain type"] == "RD"]
soto_RDs["Start"] = soto_RDs["Coordinates"].str.split("-").str[0]
soto_RDs["End"] = soto_RDs["Coordinates"].str.split("-").str[1]
soto_RDs  = soto_RDs[["Uniprot ID", "Sequence", "Start", "End"]]
soto_RDs

/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_96405/4168646088.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  soto_RDs["Start"] = soto_RDs["Coordinates"].str.split("-").str[0]
/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_96405/4168646088.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  soto_RDs["End"] = soto_RDs["Coordinates"].str.split("-").str[1]

    Uniprot ID                                           Sequence Start   End
0       Q6ZN18  AICFNLSAHIESLGKGHSVVFHSTVIAKRKEDSGKIKLLLHWMPED...   410   494
1       Q8WYP5  QEMDEGSQSLEKLDVSKGNSSVSITSDETTLEYQDAPSPEDLEETV...  1289  1444
3       Q8WYP5  DRDPRLRERSLARNSILDQYGKILPRVHRKLAIERAKPYHLSTSSV...   981  1146
16      Q96QS3  MSNQYQEEGCSERPECKSKSPTLLSSYCIDSILGRRSPCKMRLLGA...     1    66
17      Q96QS3  FPGPLSATHPLSPYLDASPFPPHHPALDSAWTAAAAAAAAAFPSLP...   400   495
..         ...                                                ...   ...   ...
917     P17098  DEGVAGVMSVGPPAARLQEPVTFRDVAVDFTQEEWGQLDPTQRILY...     5   116
918     Q0VGE8  MLREEATKKSKEKEPGMALPQGRLTFRDVAIEFSLEEWKCLNPAQR...     1   118
919     Q03923  MGPLTFRDVAIEFSLKEWQCLDTAQRNLYRNVMLENYRNLVFLGIT...     1    77
920     A6NK75  MLENYRNLVFVGIAASKPDLITCLEQGKEPWNVKRHEMVTEPPVVY...    42   145
921     Q8NAM6  MALDLRTIFQCEPSENNLGSENSAFQQSQGPAVQREEGISEFSRMV...     1   126

[389 rows x 4 columns]

In [20]:
soto_RDs.to_csv("../data/ie_files/domain_list1_Soto.csv")

In [9]:
delrosso = pd.read_excel("../data/Stanford_Supplementary Table 2 Domains from Tiles.xlsx", sheet_name = "Repression Domains")
delrosso = delrosso.rename(columns = {"UniProt ID" : "Uniprot ID"})
delrosso = delrosso[["Uniprot ID", "Sequence", "Start", "End"]]
delrosso

     Uniprot ID                                           Sequence  Start  End
0        Q9NQ94  RYTRGTGGRGTMLQGEYTYSLGQVYDPTTTYLGAPVFYAPQTYAAI...    311  410
1        Q6UWZ7  SGFVLGALAFQHLNTDSDTEGFLLGEVKGEAKNSITDSQMDDVEVV...     11   90
2        Q6UWZ7  TVSGSCMSTGFSRAVQTHSSKFFEEDGSLKEVHKINEMYASLQEEL...    181  260
3        Q15018  GVMKDIRAIYQVYNALQEKVQAVCADVEKSERVVESCQAEVNKLRR...    201  280
4        P10070  KPYKCQQPKKAFRYHPSFRTQERNHTGEKPYACKECGKTFISHSGI...    161  240
...         ...                                                ...    ...  ...
3895     A6NGD5  QILDMLVMEQFMISMPQELQVLVMMNGVQSCKDLEDLLRNNRRPKK...     81  200
3896     O15535  LLTMKVEAKSHLQWQESRLKRSNPLAREIFRRHFRQLCYQETPGPR...     21  120
3897     P10070  SGGYKQQQLRNMEIEVNRGRMPPSEFHRRKADMMESLALGFDDGKT...    271  350
3898     Q2QGD7  QQGSFSVDDVQTVSAGALGCLVALPMKNLSDDPLALTSNSNLAAHI...    591  730
3899     Q2QGD7  NSWLCGSLVVPSGGRPGPAPAAGVQCGAQGVQVQLVQDDPSGEGVL...    761  840

[3900 rows x 4 columns]

In [21]:
delrosso.to_csv("../data/ie_files/repression_domain_list_DelRosso.csv")

In [22]:
tycko = pd.read_excel("../data/tycko_1-s2.0-S0092867420315415-mmc4.xlsx", sheet_name = "Tiling Repressors")
tycko = tycko[tycko["Hit"]]
tycko = tycko.rename(columns = {"UniProt ID" : "Uniprot ID", "start" : "Start", "end" : "End"})
tycko = tycko[["Uniprot ID", "Sequence", "Start", "End"]]
tycko

,Uniprot ID,Sequence,Start,End
88,A9YTQ3,AGATTCGCCACCAGGGGCTACCCCATGGAGGACATGAAGCTGCAGG...,520,600
89,A9YTQ3,GACATGAAGCTGCAGGGCGTGCCCATGCCTCCCGGCGACCTGTGTG...,530,610
90,A9YTQ3,CCCGGCGACCTGTGCGGCCCCACCCTGCTGCTGGACGTGAGCATCA...,540,620
91,A9YTQ3,CTGGACGTGAGCATCAAGATGGAGAAGGACAGCGGCTGCGAGGGAG...,550,630
227,Q6VMQ6,ATGGACAGCCTGGAGGAGCCCCAGAAGAAGGTGTTCAAGGCCAGAA...,0,80
...,...,...,...,...
10484,P10072,ATGAGGGTGAACCACACCGTGAGCACCATGCTGCCCACCTGCATGG...,0,80
10485,P10072,ATGAGCTGCAGCGGCGCCGGCGGCATCACCGCCTTCGTGGCCTTCA...,20,100
10486,P10072,GCCTTCGTGGCCTTCAGGGACGTGGCCGTGTACTTCACCCAGGAGG...,30,110
10505,P10072,CACAGCGGCCTGAAGCCCTACGTGTGCAAGGAGTGCGGCCAGAGCT...,350,430
10513,P10073,GTGAAGGTGGAGGAGGAGGAGGAGGCCAGCCTGAGCCAGGGCGGCG...,20,100

In [23]:
tycko.to_csv("../data/ie_files/tycko_list_with_protein_sequences.csv")