In [1]:
import pandas as pd

In [16]:
SFARI_ADs = pd.read_csv("../output/SFARI_ADs_considering_isoforms_and_canonical.csv", index_col = 0)
SFARI_ADs

,Gene,Start,End,uniprotID,Matching Isoforms,Canonical Transcript ID,orig_uniprotID,Reference,TileType,ProteinRegionSeq,Notes
15,AR,1,494,P10275,"[['P10275', 'P10275-3', 'P10275-4']]",NaN,P10275,"PMID: 9033395, 7706276, Soto",TF,MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAAS...,NaN
16,AR,652,910,P10275,[['P10275']],NaN,P10275,"PMID: 9033395, Soto",TF,PTEETTQKLTVSHIEGYECQPIFLNVLEAIEPGVVCAGHDNNQPDS...,NaN
20,ARNT2,524,717,Q9HBZ2,[['Q9HBZ2']],NaN,Q9HBZ2,"PMID: 8657146, Soto",TF,QGSPFPSGHSGKAFSSSVVHVPGVNDIQSSSSTGQNMSQISRQLNQ...,NaN
22,ARX,472,562,Q96QS3,[['Q96QS3']],NaN,Q96QS3,"PMID: 17331656, Soto",TF,RHPAFISPAFGRLFSTMAPLTSASTAAALLRQPTPAVEGAVASGAL...,NaN
45,C2D1A,22,60,Q6P1N0,"[['Q6P1N0', 'Q6P1N0-2']]",NaN,Q6P1N0,Staller Activity Data,TF,GLLVDLSPDGLMIPEDGANDEELEAEFLALVGGQPPALE,NaN
...,...,...,...,...,...,...,...,...,...,...,...
662,THRA,1,52,P10827,"[['P10827', 'P10827-2', 'P10827-3', 'P10827-4']]",NaN,P10827,"PMID: 27347890, Soto",TF,MEQKPSKVECGSDPEENSARSPDGKRKRKNGQCSLKTSMSGYIPSY...,NaN
691,VDR,415,427,P11473,[['P11473']],NaN,P11473,"PMID: 15908514, Soto",TF,TPLVLEVFGNEIS,NaN
692,VDR,195,238,P11473,"[['P11473'], ['P11473']]",nan / nan,P11473 / P11473,"Choi 2000 list OR uniprot. check, GSL / Stalle...",TF,DMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,NaN
699,YY1,1,69,P25490,[['P25490']],NaN,P25490,"PMID: 7731805, Soto",TF,MASGDTLYIATDGSEMPAEIVELHEIEVETIPVETIETTVVGEEEE...,NaN
700,YY1,371,397,P25490,[['P25490']],NaN,P25490,"activation_regions.txt, GSL",TF,RTHVRIHTGDRPYVCPFDGCNKKFAQS,NaN

In [4]:
sibling_result = pd.read_csv("../output/sibling_analysis_results_fixed.csv")
sibling_result

,gene-symbol,all_proband AD_vs_DBD_sig,all_proband AD_vs_IDR_sig,all_proband AD_vs_TF_sig,all_sibling AD_vs_DBD_sig,all_sibling AD_vs_IDR_sig,all_sibling AD_vs_TF_sig,proband_only AD_vs_DBD_sig,proband_only AD_vs_IDR_sig,proband_only AD_vs_TF_sig,sibling_only AD_vs_DBD_sig,sibling_only AD_vs_IDR_sig,sibling_only AD_vs_TF_sig,hit_count,cc
0,MEIS2,True,False,True,True,False,True,True,False,False,False,False,False,5,True
1,MTF1,True,False,True,True,False,False,True,False,False,False,False,False,4,False
2,RORA,False,True,True,False,False,False,False,True,True,False,False,False,4,False
3,CASZ1,True,False,True,False,False,False,True,False,True,False,False,False,4,False
4,PAX6,True,False,True,True,False,True,False,False,False,False,False,False,4,True
5,MYT1L,True,False,False,True,False,False,True,False,False,False,False,False,3,False
6,YY1,True,False,True,False,False,False,True,False,False,False,False,False,3,False
7,HIVEP3,True,False,False,True,False,True,False,False,False,False,False,False,3,False
8,ARX,True,False,False,False,False,False,True,False,False,False,False,False,2,False
9,NR4A2,False,True,True,False,False,False,False,False,False,False,False,False,2,True
10,PAX5,True,False,False,False,False,False,True,False,False,False,False,False,2,True
11,ERG,True,False,False,False,False,False,True,False,False,False,False,False,2,True
12,PITX1,True,False,False,False,False,False,True,False,False,False,False,False,2,True
13,TFE3,True,False,True,False,False,False,False,False,False,False,False,False,2,False
14,IKZF1,True,False,False,False,False,False,False,False,False,False,False,False,1,True
15,KLF16,True,False,False,False,False,False,False,False,False,False,False,False,1,False
16,KLF7,True,False,False,False,False,False,False,False,False,False,False,False,1,False
17,GLIS1,True,False,False,False,False,False,False,False,False,False,False,False,1,False
18,NKX2-2,True,False,False,False,False,False,False,False,False,False,False,False,1,True
19,OTX1,False,False,False,False,False,False,True,False,False,False,False,False,1,False
20,CAMTA2,True,False,False,False,False,False,False,False,False,False,False,False,1,True
21,SRCAP,False,True,False,False,False,False,False,False,False,False,False,False,1,False
22,ARNT2,True,False,False,False,False,False,False,False,False,False,False,False,1,False

In [25]:
proband_only_hits = sibling_result[sibling_result["proband_only AD_vs_DBD_sig"] 
| sibling_result["proband_only AD_vs_TF_sig"]
| sibling_result["proband_only AD_vs_IDR_sig"]]
proband_only_hits

,gene-symbol,all_proband AD_vs_DBD_sig,all_proband AD_vs_IDR_sig,all_proband AD_vs_TF_sig,all_sibling AD_vs_DBD_sig,all_sibling AD_vs_IDR_sig,all_sibling AD_vs_TF_sig,proband_only AD_vs_DBD_sig,proband_only AD_vs_IDR_sig,proband_only AD_vs_TF_sig,sibling_only AD_vs_DBD_sig,sibling_only AD_vs_IDR_sig,sibling_only AD_vs_TF_sig,hit_count,cc
0,MEIS2,True,False,True,True,False,True,True,False,False,False,False,False,5,True
1,MTF1,True,False,True,True,False,False,True,False,False,False,False,False,4,False
2,RORA,False,True,True,False,False,False,False,True,True,False,False,False,4,False
3,CASZ1,True,False,True,False,False,False,True,False,True,False,False,False,4,False
5,MYT1L,True,False,False,True,False,False,True,False,False,False,False,False,3,False
6,YY1,True,False,True,False,False,False,True,False,False,False,False,False,3,False
8,ARX,True,False,False,False,False,False,True,False,False,False,False,False,2,False
10,PAX5,True,False,False,False,False,False,True,False,False,False,False,False,2,True
11,ERG,True,False,False,False,False,False,True,False,False,False,False,False,2,True
12,PITX1,True,False,False,False,False,False,True,False,False,False,False,False,2,True
19,OTX1,False,False,False,False,False,False,True,False,False,False,False,False,1,False

In [28]:
for col in sibling_result.columns:
    if col.startswith("proband_only") and sibling_result[col].dtype == bool:
        print(f"Gene symbols where {col} is True:")
        print(sibling_result[sibling_result[col]]["gene-symbol"].tolist())
        print()

Gene symbols where proband_only AD_vs_DBD_sig is True:
['MEIS2', 'MTF1', 'CASZ1', 'MYT1L', 'YY1', 'ARX', 'PAX5', 'ERG', 'PITX1', 'OTX1']

Gene symbols where proband_only AD_vs_IDR_sig is True:
['RORA']

Gene symbols where proband_only AD_vs_TF_sig is True:
['RORA', 'CASZ1']

In [26]:
hit_ADs = SFARI_ADs[SFARI_ADs["Gene"].isin(proband_only_hits["gene-symbol"])]
hit_ADs = hit_ADs[["Gene", "uniprotID", "Start", "End", "ProteinRegionSeq", "Reference"]]
hit_ADs

,Gene,uniprotID,Start,End,ProteinRegionSeq,Reference
22,ARX,Q96QS3,472,562,RHPAFISPAFGRLFSTMAPLTSASTAAALLRQPTPAVEGAVASGAL...,"PMID: 17331656, Soto"
50,CASZ1,Q86V15,31,185,LNAICAKLSRQVVVEKRADAGSHTEGSPSQPRDQERSGPESGAARA...,"PMID: 22331471, 26296975, Soto"
125,ERG,P11308,433,479,PHPPALPVTSSSFFAAPNPYWNSPTGGIYPNTRLPTSHMPSHLGTYY,"PMID: 9681824, Soto"
126,ERG,P11308,118,261,MTTNERRVIVPADPTLWSTDHVRQWLEWAVKEYGLPDVNILLFQNI...,"PMID: 14603248, Soto / DelRosso et al."
333,MEIS2,O14770,340,477,DQSNRAGFLLDPSVSQGAAYSPEGQPMGSFVLDGQQHMGIRPAGLQ...,"activation_regions.txt, GSL"
348,MTF1,Q14872,510,624,AAVASAVAAPAPPQSTTEPLPAMVQTLPLGANSVLTNNPTITITPT...,"PMID: 7610056, Soto"
349,MTF1,Q14872,328,509,GSEDTNHSLCLSDLSLLSTDSELRENSSTTQGQDLSTISPAIIFES...,"PMID: 7610056, Soto / PMID: 7610056, Soto"
367,MYT1L,Q9UL68,152,425,EEEEEEEEEEEEEEEENEDHQMNCHNTRIMQDTEKDDNNNDEYDNY...,DelRosso et al. / DelRosso et al. / PMID: 2929...
449,OTX1,P32242,172,354,AASSIWSPASISPGSAPASVSVPEPLAAPSNTSCMQRSVAAGAATA...,"PMID: 19890851, Soto"
459,PAX5,Q02548,304,358,GRDLASTTLPGYPPHVPPAGQGSYSAPTLTGMVPGSEFSGSPYSHP...,"PMID: 8617244, Soto / Choi 2000 list, GSL"
476,PITX1,P78337,234,283,VPGMPNSGLNNINNLTGSSLNSAMSPGACPYGTPASPYSVYRDTCN...,"PMID: 12242290, Soto"
539,RORA,P35398,272,385,ELEHLAQNISKSHLETCQYLREELQQITWQTFLQEEIENYQNKQRE...,"PMID: 10478845, Soto"
699,YY1,P25490,1,69,MASGDTLYIATDGSEMPAEIVELHEIEVETIPVETIETTVVGEEEE...,"PMID: 7731805, Soto"
700,YY1,P25490,371,397,RTHVRIHTGDRPYVCPFDGCNKKFAQS,"activation_regions.txt, GSL"

In [27]:
hit_ADs.to_csv("../output/proband_only_hit_iwes_v3_SFARI_ADs.csv")