In [4]:
import math
from itertools import groupby
from operator import itemgetter
import os
import glob

def split_coords(data, strand):
	# https://stackoverflow.com/questions/3149440/splitting-list-based-on-missing-numbers-in-a-sequence
	output = []
	if strand == "-" or strand == "-1" or strand == -1:
		data.reverse()
	for k, g in groupby(enumerate(data), lambda i_x: i_x[0] - i_x[1]):
		output.append(list(map(itemgetter(1), g)))
	return output

directory = "../outputs/mutations/cds_bed_format"
files = os.listdir(directory)

import sys
with open("../outputs/all_TFs_table_proteins_with_IDR.txt") as f1:
    f1.readline()
    for line in f1:
        line = line.rstrip().split("\t")
        tf, dbd_coords, ad_coords, rd_coords, bif_coords, length, idr_coords = line[3], line[6].split(","), line[7].split(","), line[8].split(","), line[9].split(","), len(line[-2]), line[11].split(',')
        
        if tf == "Q15583-2":
            continue
            
        ensg, enst = line[4], line[5]

        if "../outputs/mutations/cds_bed_format/" + enst not in glob.glob("../outputs/mutations/cds_bed_format/*"):
            print("no cds for " + enst)
        else:
            
            # Get coordinates of domains
            dbd_dom, ad_dom, rd_dom, bif_dom, idr_dom = [], [], [], [], []
    
            if dbd_coords != ["NA-NA"]:
                for coord in dbd_coords:
                    coord = coord.split("-")
                    start, end = int(coord[0]), int(coord[1])
                    dbd_dom.append((start, end))
            if ad_coords != [""]:
                for coord in ad_coords:
                    coord = coord.split("-")
                    start, end = int(coord[0]), int(coord[1])
                    ad_dom.append((start, end))
            if rd_coords != [""]:
                for coord in rd_coords:
                    coord = coord.split("-")
                    start, end = int(coord[0]), int(coord[1])
                    rd_dom.append((start, end))
            if bif_coords != [""]:
                for coord in bif_coords:
                    coord = coord.split("-")
                    start, end = int(coord[0]), int(coord[1])
                    bif_dom.append((start, end))
            if idr_coords != ["NA-NA"]:
                for coord in idr_coords:
                    coord = coord.split("-")
                    start, end = int(coord[0]), int(coord[1])
                    idr_dom.append((start, end))

            all_doms = {"DBD": dbd_dom, "AD": ad_dom, "RD": rd_dom, "Bif": bif_dom, "IDR": idr_dom}
    
            
            with open("../outputs/mutations/cds_bed_format/" + enst) as f2:
    
                coords = []
                nt_length = 0
                for line in f2:
                    line = line.rstrip().split("\t")
                    #print(line)
                    strand = line[4]
                    chrom = line[0]
                    # If the negative strand: switch the end and start of the exons  
                    if strand == "-" or strand == "-1" or strand == -1:
                        start, end = int(line[2]), int(line[1]) + 1
                    else:
                        start, end = int(line[1]) + 1, int(line[2])
    
                    coords.append((start, end))
                    nt_length += abs(end - start) + 1
    
                aa_length = int(nt_length/3)
                #if length != aa_length:
                    #print(tf, length, aa_length)
                    #continue
    
                n_exons = len(coords)
                #SK: commented next two lines out
    #             if strand == "-":
    #                 coords.reverse()
                # Sort in increasing order 
                if strand == "-" or strand == "-1" or strand == -1:
                    coords.sort(key=lambda _: -1 * _[0])
    
    
                #print(tf, n_exons, strand)
    
                dict_aa_coords = {}
                all_pos = []
                for start, end in coords:
                    if strand == "+" or strand == "1" or strand == 1:
                        all_pos += list(range(start, end + 1))
                    elif strand == "-" or strand == "-1" or strand == -1:
                        all_pos += list(range(start, end -1, -1))
                start_codon = 0
                for i in range(aa_length):
                    end_codon = start_codon +3
                    dict_aa_coords[i+1] = all_pos[start_codon : end_codon]
                    start_codon += 3
                    
                with open("../outputs/mutations/domains_bed_format/" + tf, "w") as o1:
                    print(tf)
                    #print(strand)
                    for name, domain in all_doms.items():
                        if domain == []:
                            continue
                        #print(name, domain)
                        for start_dom, end_dom in domain:
                            #print(start_dom, end_dom, domain)
                            dom_pos = []
                            for aa in range(start_dom, end_dom +1):
                                if aa <= len(dict_aa_coords):
                                    dom_pos += dict_aa_coords[aa]
                                else:
                                    print("WARNING")
                                    print(tf)
                                    print("Trying to add " + str(aa))
                                    print("but protein has length " + str(len(dict_aa_coords)))
                            for cds_dom in split_coords(dom_pos, strand):
                                start_bed = cds_dom[0] - 1
                                end_bed = cds_dom[-1]
                                o1.write(str(chrom) + "\t" + str(start_bed) + "\t" + str(end_bed) + "\t" + name + "\t" + ensg + "\t.\t" + strand + "\t" + enst + "\n")
                                #print('writing')
                                #print(tf, name, start_bed, end_bed)

A0A087WUV0
A0AVK6
A1YPR0
A2RRD8
A2RU54
A4D1E1
A6NCS4
A6NFI3
A6NFQ7
A6NGD5
A6NHJ4
A6NHT5
A6NI15
A6NJG6
A6NJL1
A6NJT0
A6NK53
A6NK75
A6NKF2
A6NLW8
A6NM28
A6NMT0
A6NN14
A6NNA5
A6NP11
A8MQ14
A8MT65
A8MTJ6
A8MTQ0
A8MTY0
A8MUV8
A8MUZ8
A8MXY4
A8MYZ6
B2RXF5
B4DU55
B4DX44
B4DXR9
B7Z6K7
C9JLR9
C9JN71
E7ETH6
E9PGG2
O00110
O00358
O00570
O14503
O14529
O14627
O14753
O14813
O14867
O14978
O15060
O15062
O15090
no cds for ENST00000383196
O15353
O15370
O15391
O15499
O15516
O15522
O15525
O43186
O43248
O43296
O43298
O43361
O43364
O43365
O43623
O43638
O43680
O43711
O43763
O43823
O43829
O60284
O60422
O60479
O60519
O60548
O60675
O60682
O60765
O60806
O75132
O75333
O75360
O75362
O75364
O75373
O75467
O75593
O75603
O94892
O95076
O95096
O95201
O95231
O95343
O95365
O95409
O95416
O95475
O95625
O95863
O95935
O95948
O96004
O96006
P04198
P05412
P07199
P09016
P09017
P09067
P09629
P0C7M4
P0CB33
P0CF97
P0CG23
P0CG24
P0CG40
P0CH99
P0CI00
P0CJ78
P0CJ79
P0DKX0
P10071
P10073
P10074
P10075
P10588
P10589
P10914
P11831
P12755
P12980
P13349
P13682
P14652
P15036
P15172
P15173
P17017
P17019
P17020
P17024
P17026
P17029
P17031
P17032
P17041
P17098
P17275
P17481
P17482
P17483
P17535
P18146
P18848
P18850
P19622
P20264
P20393
P20719
P21506
P22670
P23025
P23409
P24278
P25208
P25490
P28356
P28358
P28360
P31249
P31267
P31268
P31269
P31270
P31271
P31273
P31274
P31275
P31276
P31277
P31629
P32242
no cds for ENST00000610440
P35453
P35548
P35713
P35716
P35869
P40425
P41212
P41225
P41970
P48431
P48436
P48443
P48742
P49716
P49910
P50222
P50458
P50553
P51504
P51508
P51523
P51692
P51786
P52737
P52746
P52945
P52951
P52954
P53567
P55316
P55318
P55771
P56915
P57071
WARNING
P57071
Trying to add 1209
but protein has length 1208
WARNING
P57071
Trying to add 1210
but protein has length 1208
WARNING
P57071
Trying to add 1211
but protein has length 1208
WARNING
P57071
Trying to add 1212
but protein has length 1208
WARNING
P57071
Trying to add 1213
but protein has length 1208
WARNING
P57071
Trying to add 1214
but protein has length 1208
WARNING
P57071
Trying to add 1215
but protein has length 1208
WARNING
P57071
Trying to add 1216
but protein has length 1208
WARNING
P57071
Trying to add 1217
but protein has length 1208
WARNING
P57071
Trying to add 1218
but protein has length 1208
WARNING
P57071
Trying to add 1219
but protein has length 1208
WARNING
P57071
Trying to add 1225
but protein has length 1208
WARNING
P57071
Trying to add 1226
but protein has length 1208
WARNING
P57071
Trying to add 1227
but protein has length 1208
WARNING
P57071
Trying to add 1228
but protein has length 1208
WARNING
P57071
Trying to add 1229
but protein has length 1208
WARNING
P57071
Trying to add 1230
but protein has length 1208
WARNING
P57071
Trying to add 1231
but protein has length 1208
WARNING
P57071
Trying to add 1232
but protein has length 1208
WARNING
P57071
Trying to add 1233
but protein has length 1208
WARNING
P57071
Trying to add 1234
but protein has length 1208
WARNING
P57071
Trying to add 1235
but protein has length 1208
WARNING
P57071
Trying to add 1236
but protein has length 1208
WARNING
P57071
Trying to add 1237
but protein has length 1208
WARNING
P57071
Trying to add 1238
but protein has length 1208
WARNING
P57071
Trying to add 1239
but protein has length 1208
WARNING
P57071
Trying to add 1240
but protein has length 1208
WARNING
P57071
Trying to add 1241
but protein has length 1208
WARNING
P57071
Trying to add 1242
but protein has length 1208
WARNING
P57071
Trying to add 1243
but protein has length 1208
WARNING
P57071
Trying to add 1244
but protein has length 1208
WARNING
P57071
Trying to add 1245
but protein has length 1208
WARNING
P57071
Trying to add 1246
but protein has length 1208
WARNING
P57071
Trying to add 1247
but protein has length 1208
WARNING
P57071
Trying to add 1248
but protein has length 1208
WARNING
P57071
Trying to add 1242
but protein has length 1208
WARNING
P57071
Trying to add 1243
but protein has length 1208
WARNING
P57071
Trying to add 1244
but protein has length 1208
WARNING
P57071
Trying to add 1245
but protein has length 1208
WARNING
P57071
Trying to add 1246
but protein has length 1208
WARNING
P57071
Trying to add 1247
but protein has length 1208
WARNING
P57071
Trying to add 1248
but protein has length 1208
WARNING
P57071
Trying to add 1249
but protein has length 1208
WARNING
P57071
Trying to add 1250
but protein has length 1208
WARNING
P57071
Trying to add 1251
but protein has length 1208
WARNING
P57071
Trying to add 1252
but protein has length 1208
WARNING
P57071
Trying to add 1253
but protein has length 1208
WARNING
P57071
Trying to add 1254
but protein has length 1208
WARNING
P57071
Trying to add 1255
but protein has length 1208
WARNING
P57071
Trying to add 1256
but protein has length 1208
WARNING
P57071
Trying to add 1257
but protein has length 1208
WARNING
P57071
Trying to add 1258
but protein has length 1208
WARNING
P57071
Trying to add 1259
but protein has length 1208
WARNING
P57071
Trying to add 1260
but protein has length 1208
WARNING
P57071
Trying to add 1261
but protein has length 1208
WARNING
P57071
Trying to add 1262
but protein has length 1208
WARNING
P57071
Trying to add 1263
but protein has length 1208
WARNING
P57071
Trying to add 1264
but protein has length 1208
WARNING
P57071
Trying to add 1265
but protein has length 1208
WARNING
P57071
Trying to add 1266
but protein has length 1208
WARNING
P57071
Trying to add 1267
but protein has length 1208
WARNING
P57071
Trying to add 1268
but protein has length 1208
WARNING
P57071
Trying to add 1269
but protein has length 1208
WARNING
P57071
Trying to add 1270
but protein has length 1208
WARNING
P57071
Trying to add 1271
but protein has length 1208
WARNING
P57071
Trying to add 1272
but protein has length 1208
WARNING
P57071
Trying to add 1273
but protein has length 1208
WARNING
P57071
Trying to add 1274
but protein has length 1208
WARNING
P57071
Trying to add 1275
but protein has length 1208
WARNING
P57071
Trying to add 1276
but protein has length 1208
WARNING
P57071
Trying to add 1277
but protein has length 1208
WARNING
P57071
Trying to add 1278
but protein has length 1208
WARNING
P57071
Trying to add 1279
but protein has length 1208
WARNING
P57071
Trying to add 1280
but protein has length 1208
WARNING
P57071
Trying to add 1281
but protein has length 1208
WARNING
P57071
Trying to add 1282
but protein has length 1208
WARNING
P57071
Trying to add 1283
but protein has length 1208
WARNING
P57071
Trying to add 1284
but protein has length 1208
WARNING
P57071
Trying to add 1285
but protein has length 1208
WARNING
P57071
Trying to add 1286
but protein has length 1208
WARNING
P57071
Trying to add 1287
but protein has length 1208
WARNING
P57071
Trying to add 1288
but protein has length 1208
WARNING
P57071
Trying to add 1289
but protein has length 1208
WARNING
P57071
Trying to add 1290
but protein has length 1208
WARNING
P57071
Trying to add 1291
but protein has length 1208
WARNING
P57071
Trying to add 1292
but protein has length 1208
WARNING
P57071
Trying to add 1293
but protein has length 1208
WARNING
P57071
Trying to add 1294
but protein has length 1208
WARNING
P57071
Trying to add 1295
but protein has length 1208
WARNING
P57071
Trying to add 1296
but protein has length 1208
WARNING
P57071
Trying to add 1297
but protein has length 1208
WARNING
P57071
Trying to add 1298
but protein has length 1208
WARNING
P57071
Trying to add 1299
but protein has length 1208
WARNING
P57071
Trying to add 1300
but protein has length 1208
WARNING
P57071
Trying to add 1301
but protein has length 1208
WARNING
P57071
Trying to add 1302
but protein has length 1208
WARNING
P57071
Trying to add 1303
but protein has length 1208
WARNING
P57071
Trying to add 1304
but protein has length 1208
WARNING
P57071
Trying to add 1305
but protein has length 1208
WARNING
P57071
Trying to add 1306
but protein has length 1208
WARNING
P57071
Trying to add 1307
but protein has length 1208
WARNING
P57071
Trying to add 1308
but protein has length 1208
WARNING
P57071
Trying to add 1309
but protein has length 1208
WARNING
P57071
Trying to add 1310
but protein has length 1208
WARNING
P57071
Trying to add 1311
but protein has length 1208
WARNING
P57071
Trying to add 1312
but protein has length 1208
WARNING
P57071
Trying to add 1313
but protein has length 1208
WARNING
P57071
Trying to add 1314
but protein has length 1208
WARNING
P57071
Trying to add 1315
but protein has length 1208
WARNING
P57071
Trying to add 1316
but protein has length 1208
WARNING
P57071
Trying to add 1317
but protein has length 1208
WARNING
P57071
Trying to add 1318
but protein has length 1208
WARNING
P57071
Trying to add 1319
but protein has length 1208
WARNING
P57071
Trying to add 1320
but protein has length 1208
WARNING
P57071
Trying to add 1321
but protein has length 1208
WARNING
P57071
Trying to add 1322
but protein has length 1208
WARNING
P57071
Trying to add 1323
but protein has length 1208
WARNING
P57071
Trying to add 1324
but protein has length 1208
WARNING
P57071
Trying to add 1325
but protein has length 1208
WARNING
P57071
Trying to add 1326
but protein has length 1208
WARNING
P57071
Trying to add 1327
but protein has length 1208
WARNING
P57071
Trying to add 1328
but protein has length 1208
WARNING
P57071
Trying to add 1329
but protein has length 1208
WARNING
P57071
Trying to add 1330
but protein has length 1208
WARNING
P57071
Trying to add 1331
but protein has length 1208
WARNING
P57071
Trying to add 1332
but protein has length 1208
WARNING
P57071
Trying to add 1333
but protein has length 1208
WARNING
P57071
Trying to add 1334
but protein has length 1208
WARNING
P57071
Trying to add 1335
but protein has length 1208
WARNING
P57071
Trying to add 1336
but protein has length 1208
WARNING
P57071
Trying to add 1337
but protein has length 1208
WARNING
P57071
Trying to add 1338
but protein has length 1208
WARNING
P57071
Trying to add 1339
but protein has length 1208
WARNING
P57071
Trying to add 1340
but protein has length 1208
WARNING
P57071
Trying to add 1341
but protein has length 1208
WARNING
P57071
Trying to add 1342
but protein has length 1208
WARNING
P57071
Trying to add 1343
but protein has length 1208
WARNING
P57071
Trying to add 1344
but protein has length 1208
WARNING
P57071
Trying to add 1345
but protein has length 1208
WARNING
P57071
Trying to add 1346
but protein has length 1208
WARNING
P57071
Trying to add 1347
but protein has length 1208
WARNING
P57071
Trying to add 1348
but protein has length 1208
WARNING
P57071
Trying to add 1349
but protein has length 1208
WARNING
P57071
Trying to add 1350
but protein has length 1208
WARNING
P57071
Trying to add 1351
but protein has length 1208
WARNING
P57071
Trying to add 1352
but protein has length 1208
WARNING
P57071
Trying to add 1353
but protein has length 1208
WARNING
P57071
Trying to add 1354
but protein has length 1208
WARNING
P57071
Trying to add 1355
but protein has length 1208
WARNING
P57071
Trying to add 1356
but protein has length 1208
WARNING
P57071
Trying to add 1357
but protein has length 1208
WARNING
P57071
Trying to add 1358
but protein has length 1208
WARNING
P57071
Trying to add 1359
but protein has length 1208
WARNING
P57071
Trying to add 1360
but protein has length 1208
WARNING
P57071
Trying to add 1361
but protein has length 1208
WARNING
P57071
Trying to add 1362
but protein has length 1208
WARNING
P57071
Trying to add 1363
but protein has length 1208
WARNING
P57071
Trying to add 1364
but protein has length 1208
WARNING
P57071
Trying to add 1365
but protein has length 1208
WARNING
P57071
Trying to add 1366
but protein has length 1208
WARNING
P57071
Trying to add 1367
but protein has length 1208
WARNING
P57071
Trying to add 1368
but protein has length 1208
WARNING
P57071
Trying to add 1369
but protein has length 1208
WARNING
P57071
Trying to add 1370
but protein has length 1208
WARNING
P57071
Trying to add 1371
but protein has length 1208
WARNING
P57071
Trying to add 1372
but protein has length 1208
WARNING
P57071
Trying to add 1373
but protein has length 1208
WARNING
P57071
Trying to add 1374
but protein has length 1208
WARNING
P57071
Trying to add 1375
but protein has length 1208
WARNING
P57071
Trying to add 1376
but protein has length 1208
WARNING
P57071
Trying to add 1377
but protein has length 1208
WARNING
P57071
Trying to add 1378
but protein has length 1208
WARNING
P57071
Trying to add 1379
but protein has length 1208
WARNING
P57071
Trying to add 1380
but protein has length 1208
WARNING
P57071
Trying to add 1381
but protein has length 1208
WARNING
P57071
Trying to add 1382
but protein has length 1208
WARNING
P57071
Trying to add 1383
but protein has length 1208
WARNING
P57071
Trying to add 1384
but protein has length 1208
WARNING
P57071
Trying to add 1385
but protein has length 1208
WARNING
P57071
Trying to add 1386
but protein has length 1208
WARNING
P57071
Trying to add 1387
but protein has length 1208
WARNING
P57071
Trying to add 1388
but protein has length 1208
WARNING
P57071
Trying to add 1389
but protein has length 1208
WARNING
P57071
Trying to add 1390
but protein has length 1208
WARNING
P57071
Trying to add 1391
but protein has length 1208
WARNING
P57071
Trying to add 1392
but protein has length 1208
WARNING
P57071
Trying to add 1393
but protein has length 1208
WARNING
P57071
Trying to add 1394
but protein has length 1208
WARNING
P57071
Trying to add 1395
but protein has length 1208
WARNING
P57071
Trying to add 1396
but protein has length 1208
WARNING
P57071
Trying to add 1397
but protein has length 1208
WARNING
P57071
Trying to add 1398
but protein has length 1208
WARNING
P57071
Trying to add 1399
but protein has length 1208
WARNING
P57071
Trying to add 1400
but protein has length 1208
WARNING
P57071
Trying to add 1401
but protein has length 1208
WARNING
P57071
Trying to add 1402
but protein has length 1208
WARNING
P57071
Trying to add 1403
but protein has length 1208
WARNING
P57071
Trying to add 1404
but protein has length 1208
WARNING
P57071
Trying to add 1405
but protein has length 1208
WARNING
P57071
Trying to add 1406
but protein has length 1208
WARNING
P57071
Trying to add 1407
but protein has length 1208
WARNING
P57071
Trying to add 1408
but protein has length 1208
WARNING
P57071
Trying to add 1409
but protein has length 1208
WARNING
P57071
Trying to add 1410
but protein has length 1208
WARNING
P57071
Trying to add 1411
but protein has length 1208
WARNING
P57071
Trying to add 1412
but protein has length 1208
WARNING
P57071
Trying to add 1413
but protein has length 1208
WARNING
P57071
Trying to add 1414
but protein has length 1208
WARNING
P57071
Trying to add 1415
but protein has length 1208
WARNING
P57071
Trying to add 1416
but protein has length 1208
WARNING
P57071
Trying to add 1417
but protein has length 1208
WARNING
P57071
Trying to add 1418
but protein has length 1208
WARNING
P57071
Trying to add 1419
but protein has length 1208
WARNING
P57071
Trying to add 1420
but protein has length 1208
WARNING
P57071
Trying to add 1421
but protein has length 1208
WARNING
P57071
Trying to add 1422
but protein has length 1208
WARNING
P57071
Trying to add 1423
but protein has length 1208
WARNING
P57071
Trying to add 1424
but protein has length 1208
WARNING
P57071
Trying to add 1425
but protein has length 1208
WARNING
P57071
Trying to add 1426
but protein has length 1208
WARNING
P57071
Trying to add 1427
but protein has length 1208
WARNING
P57071
Trying to add 1428
but protein has length 1208
WARNING
P57071
Trying to add 1429
but protein has length 1208
WARNING
P57071
Trying to add 1430
but protein has length 1208
WARNING
P57071
Trying to add 1431
but protein has length 1208
WARNING
P57071
Trying to add 1432
but protein has length 1208
WARNING
P57071
Trying to add 1433
but protein has length 1208
WARNING
P57071
Trying to add 1434
but protein has length 1208
WARNING
P57071
Trying to add 1435
but protein has length 1208
WARNING
P57071
Trying to add 1436
but protein has length 1208
WARNING
P57071
Trying to add 1437
but protein has length 1208
WARNING
P57071
Trying to add 1438
but protein has length 1208
WARNING
P57071
Trying to add 1439
but protein has length 1208
WARNING
P57071
Trying to add 1440
but protein has length 1208
WARNING
P57071
Trying to add 1441
but protein has length 1208
WARNING
P57071
Trying to add 1442
but protein has length 1208
WARNING
P57071
Trying to add 1443
but protein has length 1208
WARNING
P57071
Trying to add 1444
but protein has length 1208
WARNING
P57071
Trying to add 1445
but protein has length 1208
WARNING
P57071
Trying to add 1446
but protein has length 1208
WARNING
P57071
Trying to add 1447
but protein has length 1208
WARNING
P57071
Trying to add 1448
but protein has length 1208
WARNING
P57071
Trying to add 1449
but protein has length 1208
WARNING
P57071
Trying to add 1450
but protein has length 1208
WARNING
P57071
Trying to add 1451
but protein has length 1208
WARNING
P57071
Trying to add 1452
but protein has length 1208
WARNING
P57071
Trying to add 1453
but protein has length 1208
WARNING
P57071
Trying to add 1454
but protein has length 1208
WARNING
P57071
Trying to add 1455
but protein has length 1208
WARNING
P57071
Trying to add 1456
but protein has length 1208
WARNING
P57071
Trying to add 1457
but protein has length 1208
WARNING
P57071
Trying to add 1458
but protein has length 1208
WARNING
P57071
Trying to add 1459
but protein has length 1208
WARNING
P57071
Trying to add 1460
but protein has length 1208
WARNING
P57071
Trying to add 1461
but protein has length 1208
WARNING
P57071
Trying to add 1462
but protein has length 1208
WARNING
P57071
Trying to add 1463
but protein has length 1208
WARNING
P57071
Trying to add 1464
but protein has length 1208
WARNING
P57071
Trying to add 1465
but protein has length 1208
WARNING
P57071
Trying to add 1466
but protein has length 1208
WARNING
P57071
Trying to add 1467
but protein has length 1208
WARNING
P57071
Trying to add 1468
but protein has length 1208
WARNING
P57071
Trying to add 1469
but protein has length 1208
WARNING
P57071
Trying to add 1470
but protein has length 1208
WARNING
P57071
Trying to add 1471
but protein has length 1208
WARNING
P57071
Trying to add 1472
but protein has length 1208
WARNING
P57071
Trying to add 1473
but protein has length 1208
WARNING
P57071
Trying to add 1474
but protein has length 1208
WARNING
P57071
Trying to add 1475
but protein has length 1208
WARNING
P57071
Trying to add 1476
but protein has length 1208
WARNING
P57071
Trying to add 1477
but protein has length 1208
WARNING
P57071
Trying to add 1478
but protein has length 1208
WARNING
P57071
Trying to add 1479
but protein has length 1208
WARNING
P57071
Trying to add 1480
but protein has length 1208
WARNING
P57071
Trying to add 1481
but protein has length 1208
WARNING
P57071
Trying to add 1482
but protein has length 1208
WARNING
P57071
Trying to add 1483
but protein has length 1208
WARNING
P57071
Trying to add 1484
but protein has length 1208
WARNING
P57071
Trying to add 1485
but protein has length 1208
WARNING
P57071
Trying to add 1486
but protein has length 1208
WARNING
P57071
Trying to add 1487
but protein has length 1208
WARNING
P57071
Trying to add 1488
but protein has length 1208
WARNING
P57071
Trying to add 1489
but protein has length 1208
WARNING
P57071
Trying to add 1490
but protein has length 1208
WARNING
P57071
Trying to add 1491
but protein has length 1208
WARNING
P57071
Trying to add 1492
but protein has length 1208
WARNING
P57071
Trying to add 1493
but protein has length 1208
WARNING
P57071
Trying to add 1494
but protein has length 1208
WARNING
P57071
Trying to add 1495
but protein has length 1208
WARNING
P57071
Trying to add 1496
but protein has length 1208
WARNING
P57071
Trying to add 1497
but protein has length 1208
WARNING
P57071
Trying to add 1498
but protein has length 1208
WARNING
P57071
Trying to add 1499
but protein has length 1208
WARNING
P57071
Trying to add 1500
but protein has length 1208
WARNING
P57071
Trying to add 1501
but protein has length 1208
WARNING
P57071
Trying to add 1502
but protein has length 1208
WARNING
P57071

In [23]:
import pandas as pd

tbl = pd.read_csv("../outputs/all_TFs_table_proteins.txt", sep = "\t")
tbl

,Unnamed: 0,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length
0,0,NaN,NaN,A6NJG6,NaN,ENST00000334384,79-135,142-315,NaN,NaN,1
1,1,NaN,NaN,A8MTJ6,NaN,ENST00000428390,145-234,369-420,NaN,NaN,1
2,2,NaN,NaN,A8MYZ6,NaN,ENST00000641094,89-178,382-491,NaN,NaN,1
3,3,NaN,NaN,A8MZ59,NaN,ENST00000640845,31-65,92-181,NaN,NaN,1
4,4,NaN,NaN,O00321,NaN,ENST00000403402,242-321,1-162,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
441,441,NaN,NaN,Q9Y5R6,NaN,ENST00000382276,72-118,172-251,NaN,NaN,1
442,442,NaN,NaN,Q9Y5W3,NaN,ENST00000248071,"272-296,302-326,332-354",1-89,NaN,NaN,1
443,443,NaN,NaN,Q9Y692,NaN,ENST00000294409,89-165,422-573,NaN,NaN,1
444,444,NaN,NaN,Q9Y6Q9,NaN,ENST00000371998,31-83,621-1424,NaN,NaN,1
445,445,NaN,NaN,Q9Y6Y1,NaN,ENST00000303635,69-182,"702-841,422-501",NaN,NaN,1

In [24]:
tbl[tbl["uniprotID"] == "Q9Y261"]

,Unnamed: 0,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length
431,431,NaN,NaN,Q9Y261,NaN,ENST00000377115,159-248,"1-93,361-457",NaN,NaN,1